import { DocumentFile, MultiAgentWorkflow, VerificationRecord, EdgeNodeStatus } from '../types';

export const INITIAL_DOCUMENTS: DocumentFile[] = [
  {
    id: 'doc-1',
    filename: 'AutoHive_Technical_Architecture_v2.4.pdf',
    fileType: 'PDF Document',
    size: '2.4 MB',
    uploadDate: '2026-07-25',
    content: `AUTOHIVE TECHNICAL ARCHITECTURE SPECIFICATION
Abstract: AutoHive is a decentralized, edge-enabled multi-agent coordination ecosystem.
Key Specifications:
1. Agent Execution Engine: Supports both server-side cloud LLM execution (Gemini 3.6 Flash) and local WASM/quantized edge LLM execution (WebLLM / 3.1-Flash-Lite).
2. Decentralized Verification Protocol (DVP): Every agent response generates a cryptographic proof hash (SHA-256 state root) broadcasted to a lightweight Merkle consensus ledger.
3. Multi-Agent Hivemind Orchestration: Directed Acyclic Graph (DAG) workflow runner allowing sequential and parallel agent execution with dynamic context pass-through.
4. Security & Privacy: End-to-end payload encryption with client-side key derivation. Zero telemetry leak when operating in Edge Mode.
5. Performance Benchmarks: Cloud LLM latency 380ms avg, Edge LLM latency 120ms avg on supported hardware. Memory footprint < 850 MB in WebLLM mode.`,
    summary: 'Comprehensive architecture overview of AutoHive covering cloud & edge LLM execution, decentralized cryptographic verification, DAG multi-agent pipelines, and security specs.'
  },
  {
    id: 'doc-2',
    filename: 'Patent_Draft_Decentralized_Agent_Verification.docx',
    fileType: 'Word Document',
    size: '1.8 MB',
    uploadDate: '2026-07-24',
    content: `INVENTION TITLE: Decentralized Cryptographic State Verification for Autonomous AI Agent Outputs
INVENTORS: AutoHive R&D Protocol Team
FIELD OF INVENTION: Artificial Intelligence Safety, Distributed Ledgers, Cryptographic State Proofs.
SUMMARY OF INVENTION:
A system and method for cryptographically validating non-deterministic output sequences generated by autonomous software agents operating in a distributed network.
CLAIM 1: A method comprising:
(a) intercepting an output payload generated by a neural network agent;
(b) computing a deterministic state hash combining the input context, prompt parameters, agent model hash, and output payload;
(c) committing said state hash into a local state tree;
(d) transmitting a Merkle proof of said state tree to a set of validator nodes;
(e) receiving cryptographic signatures from at least 66% of validator nodes confirming state consistency.
NOVELTY ASPECT: Prevents hallucination forgery and unauthorized payload tampering in multi-agent execution pipelines without exposing raw confidential context.`,
    summary: 'Patent claim specification for decentralized cryptographic state verification of AI agent outputs using state hashes, Merkle proofs, and consensus signatures.'
  },
  {
    id: 'doc-3',
    filename: 'Market_Analysis_Enterprise_Agentic_AI_2026.pdf',
    fileType: 'PDF Document',
    size: '4.1 MB',
    uploadDate: '2026-07-20',
    content: `GLOBAL ENTERPRISE AGENTIC AI MARKET REPORT 2026
Key Findings:
1. Enterprise adoption of multi-agent autonomous systems grew 280% YoY, driven by R&D, customer service, and regulatory compliance workflows.
2. 74% of Fortune 500 enterprises require "Auditability & Verification" before deploying autonomous agents for core business logic.
3. Edge LLM deployment saw a massive shift due to strict data sovereignty regulations in EU and US health/finance sectors.
4. Top ROI Use Cases:
   - Automated IP & Patent Screening (saves 40+ hours per patent file)
   - Autonomous Technical Blogging & Content Marketing
   - Real-time Document Q&A & Spec Synthesis
5. Competitive Moats: Platforms offering combined On-Device Privacy + Cloud Model Flexibility + Verifiable Ledger Audit Trails command a 3.5x valuation premium.`,
    summary: 'Market research report detailing 280% growth in multi-agent enterprise adoption, auditability requirements, edge computing shifts, and top ROI use cases.'
  }
];

export const INITIAL_WORKFLOWS: MultiAgentWorkflow[] = [
  {
    id: 'wf-1',
    name: 'R&D Idea to Patent & Blog Pipeline',
    description: 'Transform raw product ideas into a novelty check, patent claims, Warren Buffett strategy review, and a published research blog.',
    icon: '🚀',
    status: 'idle',
    currentStepIndex: 0,
    steps: [
      {
        id: 's1',
        agentId: 'usecase-brainstormer',
        title: 'Step 1: Idea Refinement & Architecture Brief',
        promptTemplate: 'Analyze this product concept, identify key technological innovations, and output a structured R&D specification brief: {{input}}',
        outputKey: 'brief',
        status: 'idle'
      },
      {
        id: 's2',
        agentId: 'patent-scout',
        title: 'Step 2: Novelty & Prior Art Screening',
        promptTemplate: 'Perform a novelty screening and prior art check for the technical claims generated in Step 1: {{brief}}',
        dependsOn: ['s1'],
        outputKey: 'patentAnalysis',
        status: 'idle'
      },
      {
        id: 's3',
        agentId: 'warren-buffett',
        title: 'Step 3: Strategic Moat & Commercial Evaluation',
        promptTemplate: 'Evaluate the economic moat, pricing power, and commercial defensibility of this innovation: {{brief}}',
        dependsOn: ['s1'],
        outputKey: 'strategyReview',
        status: 'idle'
      },
      {
        id: 's4',
        agentId: 'research-blogger',
        title: 'Step 4: Research Blog Post Synthesis',
        promptTemplate: 'Synthesize the R&D brief, patent novelty findings, and strategic analysis into an authoritative 1200-word technical blog post.',
        dependsOn: ['s1', 's2', 's3'],
        outputKey: 'blogPost',
        status: 'idle'
      }
    ]
  },
  {
    id: 'wf-2',
    name: 'Document Intelligence & Executive Briefing',
    description: 'Extract specs from uploaded documents, generate an executive summary, and craft an AEO optimization plan for web release.',
    icon: '📊',
    status: 'idle',
    currentStepIndex: 0,
    steps: [
      {
        id: 'w2-s1',
        agentId: 'content-finder',
        title: 'Step 1: Deep Document Feature Extraction',
        promptTemplate: 'Extract all primary technical specs, security protocols, and performance metrics from the uploaded files.',
        outputKey: 'extractedSpecs',
        status: 'idle'
      },
      {
        id: 'w2-s2',
        agentId: 'document-summarizer',
        title: 'Step 2: Executive Summary & Slide Outline',
        promptTemplate: 'Convert extracted technical specs into a 1-page executive summary and an 8-slide presentation outline.',
        dependsOn: ['w2-s1'],
        outputKey: 'execBrief',
        status: 'idle'
      },
      {
        id: 'w2-s3',
        agentId: 'aeo-optimization',
        title: 'Step 3: AI Search Visibility (AEO) Plan',
        promptTemplate: 'Generate an Answer Engine Optimization strategy to ensure these key specs rank prominently in AI answer engines.',
        dependsOn: ['w2-s2'],
        outputKey: 'aeoPlan',
        status: 'idle'
      }
    ]
  }
];

export const INITIAL_VERIFICATION_RECORDS: VerificationRecord[] = [
  {
    blockNumber: 1048291,
    proofHash: '0x8f4c2e9b1d7a3f5c0e2b4d6a8f1e3c5a7b9d0e2f4a6b8c1d3e5f7a9b0c2d4e6f',
    stateRoot: '0x3a9f1b2c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a',
    agentId: 'patent-scout',
    agentName: 'Patent Scout',
    taskSummary: 'Novelty check & prior art verification for Decentralized Verification Protocol',
    timestamp: '2026-07-26T09:42:15Z',
    status: 'VERIFIED',
    nodeSignatures: ['node-us-east-1', 'node-eu-central-1', 'node-ap-southeast-1']
  },
  {
    blockNumber: 1048290,
    proofHash: '0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    stateRoot: '0x7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c',
    agentId: 'warren-buffett',
    agentName: 'Warren Buffett',
    taskSummary: 'Moat analysis & ROI evaluation for Edge LLM deployment',
    timestamp: '2026-07-26T09:18:02Z',
    status: 'VERIFIED',
    nodeSignatures: ['node-us-east-1', 'node-us-west-2', 'node-eu-west-1']
  },
  {
    blockNumber: 1048289,
    proofHash: '0x4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e',
    stateRoot: '0x9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f',
    agentId: 'content-finder',
    agentName: 'Content Finder',
    taskSummary: 'Document search & specification synthesis across 3 PDF files',
    timestamp: '2026-07-26T08:55:40Z',
    status: 'VERIFIED',
    nodeSignatures: ['node-us-east-1', 'node-ap-northeast-1']
  }
];

export const INITIAL_EDGE_STATUS: EdgeNodeStatus = {
  status: 'online',
  modelName: 'AutoHive-3.1-Flash-Lite-WASM (Local Quantized 4-bit)',
  memoryUsageMB: 480,
  totalMemoryMB: 16384,
  cpuUsagePct: 14,
  averageLatencyMs: 115,
  isOfflineCapable: true,
  activeContextTokens: 128000
};
